### ISSUE TITLE
Incorrect Readme

### ISSUE THREAD

**Issue by cruse1977** [jdrew82/netbox-tunnels-plugin#1]
Hi,

 Playing with plugin dev and using yours as an example, thank you!.

 Just a tweak but in configuration.py the plugin to enable is 'netbox_tunnels' rather than netbox-tunnels-plugin

 (Latest netbox, module installed via pip3)

HTH

Chris

**Comment by jdrew82** [comment]
You are correct! I must have missed that when correcting the plugin name in the various places. Thanks for the heads up. Should be corrected now.
